### ISSUE TITLE
Message types: DEBUG, INFO, WARNING, ERROR

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/debugme#1]
Probably simply:

``` r
"!DEBUG debug message"
"!INFO  info message"
"!WARN  warning message
"!ERR   error message"
```

`WARN` or `WARNING` should both work, just like `ERR` and `ERROR`.

**Comment by gaborcsardi** [comment]
This is not so crucial, actually...

**Comment by krlmlr** [comment]
Verbosity levels would be handy e.g. for revdepcheck -- the messages that are printed when polling the queue should only be needed in verbose-verbose-verbose mode.

**Comment by gaborcsardi** [comment]
Yeah, I think there is an issue for this already, no?

**Comment by gaborcsardi** [comment]
Oh, yes, this is it. :)

**Comment by gaborcsardi** [comment]
I decided that we don't need message types, and just implemented verbosity levels, so I am closing this.
