### ISSUE TITLE
DEBUGME_OUTPUT_DIR

### ISSUE THREAD

**Issue by krlmlr** [r-lib/debugme#19]
Useful for revdepcheck, again. Ideas?

**Comment by gaborcsardi** [comment]
You can log to a file AFAIR, that might help here.

**Comment by krlmlr** [comment]
I see, the `DEBUGME_OUTPUT_FILE` env var. How about also supporting `DEBUGME_OUTPUT_DIR` that would use a separate file per process ID?

**Comment by gaborcsardi** [comment]
How about using a single file, but putting the process id in it? Then we need to do locking, though.

**Comment by krlmlr** [comment]
For revdepcheck I find separate output per process ID much more useful, plus we don't need to lock ;-)

**Comment by krlmlr** [comment]
Thanks for implementing this!
