### ISSUE TITLE
Comparison to futile.logger

### ISSUE THREAD

**Issue by nuest** [r-lib/debugme#20]
Looking forward to where this packages goes! I really like the colored output and the configuration via environment variables (reminds me of [npm's debug](https://www.npmjs.com/package/debug)).

I have no opinion yet on the non-R statements for writing logs... got to try it out.

Besides from these three points, are there any other features that set this apart from [`futile.logger`](https://cran.r-project.org/package=futile.logger) (also on GitHub)? Just thinking that if I log for logging packages for R, I only know about these two and new users who have to decide could be helped with some info.

**Comment by gaborcsardi** [comment]
There are a bunch of other: https://r-pkg.org/search.html?q=logging
