### ISSUE TITLE
debug levels? 

### ISSUE THREAD

**Issue by dpastoor** [r-lib/debugme#27]
Without straying into making debugme into a fullfledged logger, do you have thoughts on allowing at least one additional level like MESSAGE?

**Comment by gaborcsardi** [comment]
Could you use `!DEBUG`, `!!DEBUG`, etc. for this?

**Comment by dpastoor** [comment]
Yeah! that would work. Is that something that could control the debug level (eg only !!, or even better !!+) or would that need to be parsed from the stdout stream?

**Comment by gaborcsardi** [comment]
They control the debug level. `!!` means `!!+` effectively.

**Comment by dpastoor** [comment]
Ah I'm seeing this now that I'm reading the docs more carefully. This is perfect thanks!
