### ISSUE TITLE
Use comments instead of strings

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/debugme#33]
Now that CRAN will keep the source code.

**Comment by krlmlr** [comment]
Wouldn't that make instrumentation much more difficult?

**Comment by gaborcsardi** [comment]
No, that's fine. But the comments are still not always kept, so I think we'll need to close this one for now.

**Comment by gaborcsardi** [comment]
I wish we could have strings that are not added to the global string cache somehow....

**Comment by krlmlr** [comment]
We're talking about a few KB here, and a few extra entries in the hash table.
