### ISSUE TITLE
Do debug levels still work?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/debugme#40]
For some reason I couldn't make it work in a package. Reprex follows.

**Comment by gaborcsardi** [comment]
I think there is a test case for this. They are not very intuitive, though. Yes, please reprex.

**Comment by krlmlr** [comment]
CRAN version still doesn't work for me, development version works. Would a CRAN update break too much stuff?

**Comment by gaborcsardi** [comment]
I don't think so, we can have an update.
